os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11.1
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - git clone https://github.com/realm/SwiftLint && cd SwiftLint && swiftenv local 5.1 && swift build -c release && sudo cp .build/release/swiftlint /usr/local/bin/ && cd .. && rm -rf SwiftLint
script:
  - swiftlint --strict
  - swift test
